[General]
HttpPort = 10086
CQHttpUrl = "http://127.0.0.1:5700"
Proxy = "http://localhost:1080"
Owner = 2471967424

[ChatGPT]
Enable = true
Model = "gpt-3.5-turbo"
UseProxy = false
Url = "https://api.openai.com/v1/chat/completions"
AccessToken = ""

[DailyNews]
Enable = true
Time = "08:00"
GroupList = []

[HolidayRemainder]
Enable = true
Time = "14:00"
GroupList = []

[PixivPicGetter]
Enable = true
PixivProxy = "https://pixiv.cat/"
UseProxy = false

[RandomSetu]
Enable = true

[Soutu]
Enable = true
SaucenaoApi = "https://saucenao.com/search.php"
SaucenaoApiKey = ""
Results = 3



